import type { ForecastData, WeatherData } from '@/shared/types/weather';

// Generated using CHATGPT
const mockWeatherData: Record<string, WeatherData> = {
  London: {
    temperature: 15,
    feelsLike: 13,
    humidity: 78,
    pressure: 1013,
    windSpeed: 3.2,
    windDirection: 230,
    visibility: 10000,
    uvIndex: 3,
    condition: 'cloudy',
    description: 'partly cloudy',
    icon: '02d',
    timestamp: new Date(),
  },
  'New York': {
    temperature: 22,
    feelsLike: 25,
    humidity: 65,
    pressure: 1018,
    windSpeed: 2.8,
    windDirection: 180,
    visibility: 12000,
    uvIndex: 6,
    condition: 'sunny',
    description: 'clear sky',
    icon: '01d',
    timestamp: new Date(),
  },
  Tokyo: {
    temperature: 28,
    feelsLike: 32,
    humidity: 82,
    pressure: 1008,
    windSpeed: 1.5,
    windDirection: 90,
    visibility: 8000,
    uvIndex: 8,
    condition: 'rainy',
    description: 'light rain',
    icon: '10d',
    timestamp: new Date(),
  },
  Sydney: {
    temperature: 19,
    feelsLike: 18,
    humidity: 71,
    pressure: 1021,
    windSpeed: 4.1,
    windDirection: 270,
    visibility: 15000,
    uvIndex: 5,
    condition: 'sunny',
    description: 'clear sky',
    icon: '01d',
    timestamp: new Date(),
  },
  Cairo: {
    temperature: 35,
    feelsLike: 38,
    humidity: 45,
    pressure: 1015,
    windSpeed: 2.2,
    windDirection: 45,
    visibility: 9000,
    uvIndex: 10,
    condition: 'sunny',
    description: 'clear sky',
    icon: '01d',
    timestamp: new Date(),
  },
};

const mockForecastData: Record<string, ForecastData[]> = {
  London: [
    {
      date: '2024-01-15',
      maxTemp: 16,
      minTemp: 8,
      humidity: 75,
      windSpeed: 3.5,
      condition: 'cloudy',
      description: 'overcast',
      icon: '04d',
    },
    {
      date: '2024-01-16',
      maxTemp: 14,
      minTemp: 6,
      humidity: 80,
      windSpeed: 4.2,
      condition: 'rainy',
      description: 'light rain',
      icon: '10d',
    },
    {
      date: '2024-01-17',
      maxTemp: 12,
      minTemp: 4,
      humidity: 85,
      windSpeed: 5.1,
      condition: 'rainy',
      description: 'moderate rain',
      icon: '10d',
    },
    {
      date: '2024-01-18',
      maxTemp: 15,
      minTemp: 7,
      humidity: 70,
      windSpeed: 2.8,
      condition: 'cloudy',
      description: 'partly cloudy',
      icon: '02d',
    },
    {
      date: '2024-01-19',
      maxTemp: 18,
      minTemp: 10,
      humidity: 65,
      windSpeed: 2.2,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
  ],
  'New York': [
    {
      date: '2024-01-15',
      maxTemp: 24,
      minTemp: 16,
      humidity: 60,
      windSpeed: 3.2,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-16',
      maxTemp: 26,
      minTemp: 18,
      humidity: 58,
      windSpeed: 2.8,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-17',
      maxTemp: 23,
      minTemp: 15,
      humidity: 70,
      windSpeed: 4.5,
      condition: 'cloudy',
      description: 'partly cloudy',
      icon: '02d',
    },
    {
      date: '2024-01-18',
      maxTemp: 21,
      minTemp: 13,
      humidity: 75,
      windSpeed: 3.8,
      condition: 'rainy',
      description: 'light rain',
      icon: '10d',
    },
    {
      date: '2024-01-19',
      maxTemp: 25,
      minTemp: 17,
      humidity: 62,
      windSpeed: 2.5,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
  ],
  Tokyo: [
    {
      date: '2024-01-15',
      maxTemp: 30,
      minTemp: 22,
      humidity: 78,
      windSpeed: 2.1,
      condition: 'rainy',
      description: 'light rain',
      icon: '10d',
    },
    {
      date: '2024-01-16',
      maxTemp: 32,
      minTemp: 24,
      humidity: 75,
      windSpeed: 1.8,
      condition: 'cloudy',
      description: 'partly cloudy',
      icon: '02d',
    },
    {
      date: '2024-01-17',
      maxTemp: 29,
      minTemp: 21,
      humidity: 85,
      windSpeed: 3.2,
      condition: 'rainy',
      description: 'moderate rain',
      icon: '10d',
    },
    {
      date: '2024-01-18',
      maxTemp: 31,
      minTemp: 23,
      humidity: 72,
      windSpeed: 2.5,
      condition: 'cloudy',
      description: 'overcast',
      icon: '04d',
    },
    {
      date: '2024-01-19',
      maxTemp: 33,
      minTemp: 25,
      humidity: 68,
      windSpeed: 1.5,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
  ],
  Sydney: [
    {
      date: '2024-01-15',
      maxTemp: 21,
      minTemp: 15,
      humidity: 68,
      windSpeed: 4.5,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-16',
      maxTemp: 23,
      minTemp: 17,
      humidity: 65,
      windSpeed: 3.8,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-17',
      maxTemp: 20,
      minTemp: 14,
      humidity: 75,
      windSpeed: 5.2,
      condition: 'cloudy',
      description: 'partly cloudy',
      icon: '02d',
    },
    {
      date: '2024-01-18',
      maxTemp: 18,
      minTemp: 12,
      humidity: 80,
      windSpeed: 4.8,
      condition: 'rainy',
      description: 'light rain',
      icon: '10d',
    },
    {
      date: '2024-01-19',
      maxTemp: 22,
      minTemp: 16,
      humidity: 70,
      windSpeed: 3.5,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
  ],
  Cairo: [
    {
      date: '2024-01-15',
      maxTemp: 37,
      minTemp: 28,
      humidity: 42,
      windSpeed: 2.8,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-16',
      maxTemp: 39,
      minTemp: 30,
      humidity: 38,
      windSpeed: 3.2,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
    {
      date: '2024-01-17',
      maxTemp: 36,
      minTemp: 27,
      humidity: 48,
      windSpeed: 2.5,
      condition: 'cloudy',
      description: 'partly cloudy',
      icon: '02d',
    },
    {
      date: '2024-01-18',
      maxTemp: 34,
      minTemp: 25,
      humidity: 52,
      windSpeed: 3.8,
      condition: 'cloudy',
      description: 'overcast',
      icon: '04d',
    },
    {
      date: '2024-01-19',
      maxTemp: 38,
      minTemp: 29,
      humidity: 40,
      windSpeed: 2.2,
      condition: 'sunny',
      description: 'clear sky',
      icon: '01d',
    },
  ],
};

export { mockWeatherData, mockForecastData };
